"""empty message

Revision ID: 25b516b59274
Revises: 
Create Date: 2019-11-27 01:04:01.241921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b516b59274'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Handler',
    sa.Column('adminId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('adminId')
    )
    op.create_table('Hotels',
    sa.Column('hotelId', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('totalRooms', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('hotelId')
    )
    op.create_table('Users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('Facilities',
    sa.Column('hotelId', sa.String(length=10), nullable=False),
    sa.Column('gym', sa.Boolean(), nullable=True),
    sa.Column('FoodBeverages', sa.Boolean(), nullable=True),
    sa.Column('Parking', sa.Boolean(), nullable=True),
    sa.Column('Tv', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotelId'], ['Hotels.hotelId'], ),
    sa.PrimaryKeyConstraint('hotelId')
    )
    op.create_table('Rooms',
    sa.Column('hotelId', sa.String(length=10), nullable=False),
    sa.Column('roomNo', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('price', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['hotelId'], ['Hotels.hotelId'], ),
    sa.PrimaryKeyConstraint('hotelId', 'roomNo')
    )
    op.create_table('Drafts',
    sa.Column('hotelId', sa.String(length=10), nullable=False),
    sa.Column('roomNo', sa.String(length=64), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('checkIn', sa.String(length=25), nullable=True),
    sa.Column('chechOut', sa.String(length=25), nullable=True),
    sa.Column('totalMembers', sa.Integer(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paymentStatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotelId'], ['Hotels.hotelId'], ),
    sa.ForeignKeyConstraint(['roomNo'], ['Rooms.roomNo'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.userId'], ),
    sa.PrimaryKeyConstraint('hotelId', 'roomNo', 'userId')
    )
    op.create_table('Room_allotted',
    sa.Column('hotelId', sa.String(length=10), nullable=False),
    sa.Column('roomNo', sa.String(length=64), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('checkIn', sa.String(length=25), nullable=True),
    sa.Column('chechOut', sa.String(length=25), nullable=True),
    sa.Column('totalMembers', sa.Integer(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paymentStatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotelId'], ['Hotels.hotelId'], ),
    sa.ForeignKeyConstraint(['roomNo'], ['Rooms.roomNo'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.userId'], ),
    sa.PrimaryKeyConstraint('hotelId', 'roomNo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Room_allotted')
    op.drop_table('Drafts')
    op.drop_table('Rooms')
    op.drop_table('Facilities')
    op.drop_table('Users')
    op.drop_table('Hotels')
    op.drop_table('Handler')
    # ### end Alembic commands ###
