"""empty message

Revision ID: 91eceffac297
Revises: 
Create Date: 2019-10-18 01:43:16.945207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eceffac297'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('rollno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.Column('official_email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('rollno')
    )
    op.create_index(op.f('ix_Student_official_email'), 'Student', ['official_email'], unique=True)
    op.create_table('supplementary_exam',
    sa.Column('rollno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('subject_code', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('rollno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplementary_exam')
    op.drop_index(op.f('ix_Student_official_email'), table_name='Student')
    op.drop_table('Student')
    # ### end Alembic commands ###
