"""empty message

Revision ID: 997d252790cb
Revises: 49bf5d66f4df
Create Date: 2019-10-01 01:52:10.413383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997d252790cb'
down_revision = '49bf5d66f4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplementary_exam',
    sa.Column('rollno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('subject_code', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('rollno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplementary_exam')
    # ### end Alembic commands ###
