"""empty message

Revision ID: a32b5634c3a8
Revises: ae24e7842082
Create Date: 2019-11-02 00:20:47.439518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32b5634c3a8'
down_revision = 'ae24e7842082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('payment', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'payment')
    # ### end Alembic commands ###
