"""n

Revision ID: ae24e7842082
Revises: 
Create Date: 2019-11-01 00:28:20.081441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae24e7842082'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Result',
    sa.Column('rollno', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.Column('sem1', sa.String(length=256), nullable=True),
    sa.Column('sem2', sa.String(length=256), nullable=True),
    sa.Column('sem3', sa.String(length=256), nullable=True),
    sa.Column('sem4', sa.String(length=256), nullable=True),
    sa.Column('sem5', sa.String(length=256), nullable=True),
    sa.Column('sem6', sa.String(length=256), nullable=True),
    sa.Column('sem7', sa.String(length=256), nullable=True),
    sa.Column('sem8', sa.String(length=256), nullable=True),
    sa.Column('sem9', sa.String(length=256), nullable=True),
    sa.Column('sem10', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('rollno')
    )
    op.create_table('Student',
    sa.Column('rollno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.Column('official_email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('rollno')
    )
    op.create_index(op.f('ix_Student_official_email'), 'Student', ['official_email'], unique=True)
    op.create_table('enrollments',
    sa.Column('rollno', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('rollno', 'subject')
    )
    op.create_table('supplementary_exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rollno', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('subject_code', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('dept', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('supplementary_exam')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_Student_official_email'), table_name='Student')
    op.drop_table('Student')
    op.drop_table('Result')
    # ### end Alembic commands ###
